### ISSUE TITLE
in pycharm run

### ISSUE THREAD

**Issue by yangmeishu** [kerollosy/timedinput#2]
when in in pycharm run ,can not get input value 
`
  delete = timedinput("Enter something: ", timeout=5, default="n")

  print(f'you input is {delete}')
`

result:
`
Enter something: my input value

you input is n
`

**Comment by kerollosy** [comment]
1. In the main menu, go to **Run | Edit Configurations.**

2. Select the desired configuration and set the **Emulate terminal in output console** checkbox:


![image](https://github.com/user-attachments/assets/d4342f51-b9e2-4533-a612-63712311ef30)

let me know if this fixed your problem

**Comment by yangmeishu** [comment]
thanks
